### ISSUE TITLE
CMD opens and closes without updating

### ISSUE THREAD

**Issue by SirenBrink** [pilout/YuzuUpdater#3]
Obviously not working

![Screenshot 2023-05-17 195706](https://github.com/pilout/YuzuUpdater/assets/40726044/fbb0cbd9-638b-4e83-8816-12784830c806)

It complains about not finding hostpolicy.dll in "Program Files\dotnet" but that lib isn't supposed to be in there in the first place, it's under "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\ (VERSION)\"

I have dotnet v3.1.32, v5.0.17, v6.0.16, and v7.0.5

**Comment by pilout** [comment]
Tx for issue , i add a missing file to zip. Can you test it ?

**Comment by SirenBrink** [comment]
It's working now, thank you for the quick fix
