### ISSUE TITLE
[New Feature Request] Auto launch Yuzu without interference

### ISSUE THREAD

**Issue by eUnisk** [pilout/YuzuUpdater#4]
First of all, excellent work!  There are just some of my suggestions to make this project even better:

- The menu of "Do you want other things?" is slightly confusing. There's no number or short key for those options. I want to launch Yuzu, so I guess maybe just a enter key? Lucky I'm correct, but I really don't know what to do if I want to switch or download mods, what should I enter or press? We need some instructions for this part.

- For most of the time we just want to launch the Yuzu if there are no updates. So maybe set launch Yuzu automatically if there's no interference for saying 10 sec? 

That's all for now after my first day of using this. Thanks again for the excellent work.

**Comment by pilout** [comment]
I take a note. A 10 SC delay and a conf file for auto launch. Tx for tour review.

**Comment by pilout** [comment]
Done :) with 1.8.

Settings : AutoStart yuzu + auto Download
