### ISSUE TITLE
Used key list is out of date and missing many titles.

### ISSUE THREAD

**Issue by ZachAR3** [pilout/YuzuUpdater#5]
The key list used is missing tons of new titles such as new zelda, pokemon arceus, etc. I would recommend switching to processing the yuzu prod.keys file, as I am doing in mine, since I can't seem to find any other nice databases that are up to date either.

**Comment by pilout** [comment]
Hum what Do you mean. The tool dont use a Key list. He scan directory of your yuzu and search the game title hère :

https://switchbrew.org/w/index.php?title=Title_list/Games&mobileaction=toggle_view_desktop


I think all game IS registered , for exemple new zelda IS detected.

**Comment by ZachAR3** [comment]
> 

Must have been updated, When I checked last night many of the newer games were missing.
