### ISSUE TITLE
Couldn't start 1.8 version

### ISSUE THREAD

**Issue by eUnisk** [pilout/YuzuUpdater#8]
See the new version today and unzip it straight a way to the folder. Old files are overwritten. 

But can not start it, the window closed after a blink. I tried to open with admin mode but still the problem.

Any idea?

**Comment by xellos81** [comment]
same here

**Comment by pilout** [comment]
have you the 7zip folder in the same directory as exe ?

**Comment by eUnisk** [comment]
> have you the 7zip folder in the same directory as exe ?

Yes.

**Comment by pilout** [comment]
Can you retry with 1.81 ? , do you have any error message or something ?

**Comment by eUnisk** [comment]
> Can you retry with 1.81 ? , do you have any error message or something ?

Hi, I tried 1.81 however, the problem is the same. I managed to get a screenshot of the error messages. It only appears once for the first time opening after a computer restart. After that if no restart there's only black in the window. Anyway, see the attached screenshot, please.

![YuzuEAUpdater 1 81 2023-05-26 195427](https://github.com/pilout/YuzuUpdater/assets/109562613/c70dde76-7727-47ee-8b41-aeab1bbfe9c7)

**Comment by EmmanuelVella** [comment]
Same issue, a blue window opens but closes immediately with no error message. Tell me if I can help.

**Comment by pilout** [comment]
If u can provide your yuzu user folder can be nice :)

**Comment by EmmanuelVella** [comment]
You mean the one located in `C:\Users\<user>\AppData\Roaming\yuzu` ?

**Comment by pilout** [comment]
yes that it

**Comment by EmmanuelVella** [comment]
Here it is https://file.io/swS1Hoa1VCNQ (please tell me when you have downloaded it, so I remove it).

**Comment by pilout** [comment]
TX :)

**Comment by eUnisk** [comment]
> > Can you retry with 1.81 ? , do you have any error message or something ?
> 
> Hi, I tried 1.81 however, the problem is the same. I managed to get a screenshot of the error messages. It only appears once for the first time opening after a computer restart. After that if no restart there's only black in the window. Anyway, see the attached screenshot, please.
> 
> ![YuzuEAUpdater 1 81 2023-05-26 195427](https://user-images.githubusercontent.com/109562613/241187142-c70dde76-7727-47ee-8b41-aeab1bbfe9c7.png)

BTW, I installed ReShade 5.8.0, that might be the problem?

**Comment by EmmanuelVella** [comment]
FYI I have reshade too.

**Comment by pilout** [comment]
I dont think IS related to reshad.i w'll test today or later

**Comment by pilout** [comment]
No probleme with your appdata folder. I add a 1.82 release for more console error info. If you can test it

**Comment by EmmanuelVella** [comment]
I get this error : 
![image](https://github.com/pilout/YuzuUpdater/assets/663607/792aa35e-5dcc-498c-b81a-6d1419813216)

**Comment by DrR0Ck** [comment]
Same here.  Just tested 1.82 and get the following:
C:\Games\YUZU_EA>YuzuEAUpdater.exe
←[?1047h←[3J←[3JUnhandled exception. System.ArgumentOutOfRangeException: The new console window size would force the console buffer size to be too large. (Parameter 'width')
Actual value was 800.
   at System.ConsolePal.SetWindowSize(Int32 width, Int32 height)
   at System.Console.SetWindowSize(Int32 width, Int32 height)
   at YuzuEAUpdater.UI.<>c__DisplayClass18_0.<InitializeComponent>b__10()
   at Terminal.Gui.MainLoop.<>c__DisplayClass16_0.<Invoke>b__0()
   at Terminal.Gui.MainLoop.RunIdle()
   at Terminal.Gui.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
   at YuzuEAUpdater.Program.Main(String[] args)

I believe I've been getting the same errors since 1.8.  1.7 still works fine.

**Comment by eUnisk** [comment]
And hers my error message from 1.82. Plz note I ran this when Yuzu was open. 

Unhandled exception.    at YuzuEAUpdater.UI.addTextConsole(String text)
   at YuzuEAUpdater.UI.getCurrentVersion()
   at YuzuEAUpdater.UI.<.ctor>b__21_0()System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
   at YuzuEAUpdater.Program.Main(String[] args)

![YuzuEAUpdater 1 82 2023-05-26](https://github.com/pilout/YuzuUpdater/assets/109562613/81e67c29-1f16-43f0-a331-5bbfff925379)

**Comment by pilout** [comment]
Try new 1.83 please :)

**Comment by DrR0Ck** [comment]
It opened and then brought up Yuzu; I'm caught up on my EA downloads, so nothing to download just now.  I will verify all works properly once another build is released.

Thanks!!!

**Comment by EmmanuelVella** [comment]
Now it opens but stay on the blue screen with nothing happening : 
![image](https://github.com/pilout/YuzuUpdater/assets/663607/3bd195dc-e083-47a7-824e-8ed87af8d612)

**Comment by pilout** [comment]
Can't work on this now. I can mp you for help me in the futur ?

I send a mail to your adress with my discord.

**Comment by EmmanuelVella** [comment]
Sure !

**Comment by eUnisk** [comment]
I tried 1.83, here's what I got: (Win11 x64)

> Unhandled exception.    at YuzuEAUpdater.UI.addTextConsole(String text)
>    at YuzuEAUpdater.UI.getCurrentVersion()
>    at YuzuEAUpdater.UI.<.ctor>b__21_0()System.NullReferenceException: Object reference not set to an instance of an object.
>    at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
>    at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
>    at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
>    at YuzuEAUpdater.Program.Main(String[] args)

**Comment by DrR0Ck** [comment]
Well, there's a new build of Yuzu available.  But 1.83 doesn't download it.  I get the same behavior mentioned above.  Sits on a blue screen with a flashing cursor.  I think it may simply not be displaying the text; I hit enter and yuzu opens and the updater closes.

...And I can confirm it's actually working but not displaying the text (or perhaps displaying text in the same color as the background):  Hit enter opens Yuzu but hitting "y" enter updated my yuzu build as expected.

**Comment by pilout** [comment]
Ok tx for ur review i'll publish a fix this evening.

**Comment by EmmanuelVella** [comment]
I confirm the behavior described by @DrR0Ck ! It works but no text is visible.

**Comment by pilout** [comment]
i upload a news release version. If someone can tell me if its better for him and if he can give me error message he have.

**Comment by eUnisk** [comment]
Hi Mate, please see the pic. The program quits too quick to do a proper CTRL+C.

![YuzuEAUpdater 1 84 2023-05-28 011830](https://github.com/pilout/YuzuUpdater/assets/109562613/29e5e0aa-375d-43eb-acad-ef8808f25f70)

**Comment by pilout** [comment]
Tx :)  i think the ui dont initialize correctly i push a new version now.

**Comment by eUnisk** [comment]
> Tx :) i think the ui dont initialize correctly i push a new version now.

Hi mate, just did a quick test. The program opens this time. If no update it launches Yuzu automatically without any key entry. 

However, on my test when there is update it prompts y/n to upgrade Yuzu but whatever you entered (Tried Y,N, Y and Enter, N and Enter) the program cannot go on.  No error message.

**Comment by pilout** [comment]
The ui render display fine ? U have a bar with settings and mods ?

**Comment by pilout** [comment]
Ok done now :) that should work correctly

**Comment by dawnarius** [comment]
1.86 worked the first time and made the update then it closed (or maybe crashed I wasn't looking)

but now whenever I start it I throws this exception:

`Unhandled exception.    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at YuzuEAUpdater.UI.waitYuzuLaunch() in F:\oldpc\projets prog\YuzuEAUpdater\YuzuEAUpdater\Program.cs:line 503
   at YuzuEAUpdater.UI.<.ctor>b__21_0() in F:\oldpc\projets prog\YuzuEAUpdater\YuzuEAUpdater\Program.cs:line 450System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
   at YuzuEAUpdater.Program.Main(String[] args) in F:\oldpc\projets prog\YuzuEAUpdater\YuzuEAUpdater\Program.cs:line 23`

**Comment by DrR0Ck** [comment]
1.86 working fine for me so far.  Will let you know if anything changes.  Thanks for the work on this!

**Comment by eUnisk** [comment]
> The 1.85 ui render display fine ? U have a bar with settings and mods ?

Hi mate, the UI displays fine. Only seems not respond to user key entry. 

1.86 however, opens as a black window on my computer. Tried to press Y and Enter, but still no response.

**Comment by pilout** [comment]
Ok 1.87 release now :) if u can test :) tx for all your test.

**Comment by eUnisk** [comment]
Hi, I tested 1.87, works great for me.  See attached.

![YuzuEAUpdater 1 87 2023-05-26](https://github.com/pilout/YuzuUpdater/assets/109562613/99a0a8d6-a91c-4ed2-aee4-219b9503d9ae)

**Comment by pilout** [comment]
Nice :) can add new features now :) have u a idea ?

**Comment by eUnisk** [comment]
Ha! That's pretty much everything I need. But if you ask me...

I can see the Yuzu folder is growing bigger and bigger as updates. I guess that's mainly because of those .xz files. Maybe a function to make it as slim as new? 

And maybe a function to auto-update the updater itself?

![image](https://github.com/pilout/YuzuUpdater/assets/109562613/3544c92a-cb0c-4f25-a144-59376b8f41f2)

**Comment by EmmanuelVella** [comment]
Hello, I confirm it works now, thank you !

+1 to @eUnisk idea. An option to auto-update your updater would be nice too :p

**Comment by pilout** [comment]
Ok nice i w'll do that :) tx for tour review. Maybe a feature for improve performance if yuzu. I'm on research

**Comment by pilout** [comment]
Its done for updater, purge files

**Comment by EmmanuelVella** [comment]
Just tested, working great !

**Comment by eUnisk** [comment]
> Its done for updater, purge files

Tested, purge files working good, at least the .xz files are gone. Couldn't test the updateupdater as 2.0 is already the latest. 

And if we can see some message saying "purging old files..." and "Your updater is already the latest!" it will be good.

Also a little error: 2.0 is still showing itself as 1.8. 

Looking forward for a newer version and I'll see if the updater can update it by itself. ;-)

**Comment by pilout** [comment]
Is there another obselete files ?
